### ISSUE TITLE
蓝牙模块问题

### ISSUE THREAD

**Issue by Woshuo123** [codeMauguin/RedmiBook14II-i51035G1-EFI#7]
你好，点击蓝牙的时候可用打开，但是打开的时候极其缓慢，然后搜索不到设备，这个是为什么呢

**Comment by codeMauguin** [comment]
可以去这下载最新的蓝牙驱动，点击这里[作者](https://github.com/OpenIntelWireless) 我已经更新到 mac os14了我的驱动文件你可能已经不适用了，今天晚上我有空会上传上去的，我的蓝牙驱动应该是可以使用的



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "codeMauguin/RedmiBook14II-i5-1035G1-EFI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月6日(星期四) 下午4:38
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[codeMauguin/RedmiBook14II-i5-1035G1-EFI] 蓝牙模块问题 (Issue #7)





 
你好，点击蓝牙的时候可用打开，但是打开的时候极其缓慢，然后搜索不到设备，这个上为什么呢

**Comment by codeMauguin** [comment]
> 你好，点击蓝牙的时候可用打开，但是打开的时候极其缓慢，然后搜索不到设备，这个是为什么呢

**Comment by codeMauguin** [comment]
https://github.com/OpenIntelWireless
